import { notFound } from "next/navigation";
import { Check, Shield, Zap, Sparkles, ArrowRight } from "lucide-react";
import Link from "next/link";

// Mock Database of "Generated Products"
const products = {
    "modern-auth-hook": {
        name: "AuthKit Pro",
        tagline: "The last authentication hook you'll ever need.",
        price: "$29",
        features: ["Supports Clerk, Firebase, Supabase", "Role-based Redirects", "Session Persistence", "TypeScript Ready"],
        color: "from-cyan-500 to-blue-600"
    },
    "saas-pricing-table": {
        name: "PriceTable X",
        tagline: "Convert more users with psychological pricing grids.",
        price: "$49",
        features: ["Monthly/Yearly Toggle", "Best Value Highlight", "Mobile Responsive", "Tailwind Compatible"],
        color: "from-emerald-500 to-green-600"
    },
    "invoice-generator-pdf": {
        name: "InvoiceGen API",
        tagline: "Server-side PDF generation made simple.",
        price: "$19",
        features: ["HTML to PDF", "Custom Branding", "Zero Dependencies", "Fast Render"],
        color: "from-purple-500 to-indigo-600"
    }
};

export default async function LandingPage(props: { params: Promise<{ slug: string }> }) {
    const params = await props.params;
    const product = products[params.slug as keyof typeof products];

    if (!product) {
        // Fallback for demo
        return (
            <div className="min-h-screen bg-black text-white flex items-center justify-center">
                <div className="text-center">
                    <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-zinc-200 to-zinc-500 mb-4">
                        Generated Product: {params.slug}
                    </h1>
                    <p className="text-zinc-500">This landing page was auto-generated by The Forge.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-[#050505] text-white selection:bg-white/20">
            {/* Grid Background */}
            <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px]" />

            <div className="relative max-w-5xl mx-auto px-6 py-24">
                {/* Header */}
                <header className="flex items-center justify-between mb-24">
                    <div className={`w-8 h-8 rounded-lg bg-gradient-to-br ${product.color}`} />
                    <Link href="/dashboard/forge" className="text-sm text-zinc-500 hover:text-white transition-colors">
                        Built with The Forge
                    </Link>
                </header>

                {/* Hero */}
                <div className="text-center mb-24">
                    <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-medium mb-8`}>
                        <Sparkles className="w-3 h-3 text-amber-400" />
                        <span>New Release</span>
                    </div>
                    <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-8">
                        {product.name}
                    </h1>
                    <p className="text-xl text-zinc-400 max-w-2xl mx-auto mb-12">
                        {product.tagline}
                    </p>
                    <button className={`px-8 py-4 rounded-full bg-gradient-to-r ${product.color} font-bold text-white hover:scale-105 transition-transform shadow-2xl`}>
                        Buy Now for {product.price}
                    </button>
                </div>

                {/* Features */}
                <div className="grid md:grid-cols-2 gap-4 max-w-2xl mx-auto">
                    {product.features.map((feature) => (
                        <div key={feature} className="p-4 rounded-2xl bg-white/[0.03] border border-white/[0.05] flex items-center gap-3">
                            <div className="p-1 rounded-full bg-emerald-500/10 text-emerald-400">
                                <Check className="w-4 h-4" />
                            </div>
                            <span>{feature}</span>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
